// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern wird der Adapter sofort mit der neuen Konfiguration neu gestartet",
    "ru": "при сохранении адаптер перезапускается с новым конфигом немедленно",
    "pt": "ao salvar o adaptador reinicia imediatamente com a nova configuração",
    "nl": "on save adapter wordt onmiddellijk opnieuw gestart met de nieuwe configuratie",
    "fr": "lors de l'enregistrement, l'adaptateur redémarre avec la nouvelle configuration immédiatement",
    "it": "on save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "al guardar el adaptador se reinicia con la nueva configuración inmediatamente",
    "pl": "po zapisaniu adapter natychmiast uruchamia się ponownie z nową konfiguracją"
  },
  "host": {
    "en": "Host",
    "de": "Host",
    "ru": "хозяин",
    "pt": "Host",
    "nl": "Host",
    "fr": "Host",
    "it": "Host",
    "es": "Host",
    "pl": "Host"
  },
  "port": {
    "en": "port",
    "de": "Port",
    "ru": "порт",
    "pt": "porta",
    "nl": "port",
    "fr": "Port",
    "it": "porta",
    "es": "Puerto",
    "pl": "Port"
  },
  "pollInterval": {
    "en": "polling Interval",
    "de": "Abrufintervall",
    "ru": "Интервал опроса",
    "pt": "Intervalo de votação",
    "nl": "polling-interval",
    "fr": "intervalle d'interrogation",
    "it": "Intervallo di polling",
    "es": "intervalo de votación",
    "pl": "Interwał odpytywania"
  },
  "invimp": {
    "en": "inverter/undercounter request. Caution! User-password of Solarlog has to be deactivated",
    "de": "Wechselrichter- / Unterzähleranforderung. Vorsicht! Das Benutzerpasswort von Solarlog muss deaktiviert sein",
    "ru": "запрос инвертора / пониженной нагрузки. Внимание! Пароль пользователя Solarlog должен быть деактивирован",
    "pt": "solicitação do inversor / sub-contador. Cuidado! A senha do usuário do Solarlog deve ser desativada",
    "nl": "verzoek omvormer / onderbouw. Voorzichtigheid! Het gebruikerswachtwoord van Solarlog moet worden gedeactiveerd",
    "fr": "onduleur / demande sous comptoir. Mise en garde! Le mot de passe utilisateur de Solarlog doit être désactivé",
    "it": "richiesta inverter / sottopiano. Attenzione! La password utente di Solarlog deve essere disattivata",
    "es": "solicitud de inversor / bajo mostrador. ¡Precaución! La contraseña de usuario de Solarlog debe estar desactivada",
    "pl": "zapytanie o falownik / podblat. Uwaga! Hasło użytkownika Solarlog musi zostać dezaktywowane"
  },
  "Basic Settings": {
    "en": "Basic sessting:",
    "de": "Grundeinstellungen",
    "ru": "основные настройки",
    "pt": "configurações básicas",
    "nl": "basis instellingen",
    "fr": "Paramètres de base",
    "it": "impostazioni di base",
    "es": "ajustes básicos",
    "pl": "podstawowe ustawienia"
  },
  "Plant Settings": {
    "en": "plant settings",
    "de": "Anlageneinstellungen",
    "ru": "заводские настройки",
    "pt": "configurações da planta",
    "nl": "plant instellingen",
    "fr": "paramètres de l'usine",
    "it": "impostazioni dell'impianto",
    "es": "ajustes de la planta",
    "pl": "ustawienia roślin"
  },
  "Connection settings": {
    "en": "connection settings",
    "de": "Verbindungseinstellungen",
    "ru": "Настройки соединения",
    "pt": "configurações de conexão",
    "nl": "verbindingsinstellingen",
    "fr": "paramètres de connexion",
    "it": "impostazioni di connessione",
    "es": "ajustes de conexión",
    "pl": "ustawienia połączenia"
  },
  "invimp settings": {
    "en": "inverter/submeter settings",
    "de": "Wechselrichter- / Unterzählereinstellungen",
    "ru": "настройки инвертора / пониженной частоты",
    "pt": "configurações do inversor / sub-contador",
    "nl": "omvormer / onderbouw instellingen",
    "fr": "paramètres onduleur / sous comptoir",
    "it": "impostazioni inverter / sottopiano",
    "es": "ajustes del inversor / debajo del mostrador",
    "pl": "ustawienia falownika / podblatowego"
  },
  "get forecast:": {
    "en": "get forecast:",
    "de": "Prognose erhalten:",
    "ru": "получить прогноз:",
    "pt": "obter previsão:",
    "nl": "voorspelling krijgen:",
    "fr": "obtenir des prévisions:",
    "it": "ottenere previsioni:",
    "es": "obtener pronóstico:",
    "pl": "uzyskaj prognozę:"
  },
  "-90 (south) … 90 (north), deciamal separaion: point": {
    "en": "-90 (south) … 90 (north), deciamal separaion: point",
    "de": "-90 (Süden)… 90 (Norden), Deziamentrennung: Punkt",
    "ru": "-90 (юг)… 90 (север), десятичное разделение: точка",
    "pt": "-90 (sul)… 90 (norte), separação deciamal: ponto",
    "nl": "-90 (zuiden) ... 90 (noorden), deciamale scheiding: punt",
    "fr": "-90 (sud)… 90 (nord), séparation déciamale: point",
    "it": "-90 (sud)… 90 (nord), separaion deciamale: punto",
    "es": "-90 (sur) ... 90 (norte), separación deciamal: punto",
    "pl": "-90 (południe)… 90 (północ), separacja deciamalna: punkt"
  },
  " -180 (west) … 180 (east), deciamal separaion: point": {
    "en": " -180 (west) … 180 (east), deciamal separaion: point",
    "de": " -180 (Westen)… 180 (Osten), Deziamaltrennung: Punkt",
    "ru": " -180 (запад)… 180 (восток), десятичное разделение: точка",
    "pt": " -180 (oeste)… 180 (leste), separação deciamal: ponto",
    "nl": " -180 (west) ... 180 (oost), deciamale scheiding: punt",
    "fr": " -180 (ouest)… 180 (est), séparation déciamale: point",
    "it": " -180 (ovest)… 180 (est), separazione deciamale: punto",
    "es": " -180 (oeste) ... 180 (este), separación deciamal: punto",
    "pl": " -180 (zachód)… 180 (wschód), separacja deciamalna: punkt"
  },
  "latitude:": {
    "en": "latitude:",
    "de": "Breitengrad:",
    "ru": "широта:",
    "pt": "latitude:",
    "nl": "breedtegraad:",
    "fr": "latitude:",
    "it": "latitudine:",
    "es": "latitud:",
    "pl": "szerokość:"
  },
  "longitude:": {
    "en": "longitude:",
    "de": "Längengrad:",
    "ru": "долгота:",
    "pt": "longitude:",
    "nl": "Lengtegraad:",
    "fr": "longitude:",
    "it": "longitudine:",
    "es": "longitud:",
    "pl": "długość geograficzna:"
  },
  "location": {
    "en": "location",
    "de": "Standort",
    "ru": "место расположения",
    "pt": "localização",
    "nl": "plaats",
    "fr": "emplacement",
    "it": "Posizione",
    "es": "ubicación",
    "pl": "Lokalizacja"
  },
  "declination": {
    "en": "declination",
    "de": "Ausrichtung",
    "ru": "склонение",
    "pt": "declinação",
    "nl": "declinatie",
    "fr": "déclinaison",
    "it": "declinazione",
    "es": "declinación",
    "pl": "deklinacja"
  },
  "inclination:": {
    "en": "inclination:",
    "de": "Neigung:",
    "ru": "наклонение:",
    "pt": "inclinação:",
    "nl": "helling:",
    "fr": "inclination:",
    "it": "inclinazione:",
    "es": "inclinación:",
    "pl": "nachylenie:"
  },
  "azimuth:": {
    "en": "azimuth:",
    "de": "Azimut:",
    "ru": "азимут:",
    "pt": "azimute:",
    "nl": "azimuth:",
    "fr": "azimut:",
    "it": "azimut:",
    "es": "azimut:",
    "pl": "azymut:"
  },
  "0 (horizontal) … 90 (vertical)": {
    "en": "0 (horizontal) … 90 (vertical)",
    "de": "0 (horizontal)… 90 (vertikal)",
    "ru": "0 (по горизонтали)… 90 (по вертикали)",
    "pt": "0 (horizontal)… 90 (vertical)",
    "nl": "0 (horizontaal)… 90 (verticaal)",
    "fr": "0 (horizontal)… 90 (vertical)",
    "it": "0 (orizzontale)… 90 (verticale)",
    "es": "0 (horizontal) ... 90 (vertical)",
    "pl": "0 (poziomo)… 90 (pionowo)"
  },
  "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)": {
    "en": "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)",
    "de": "-180… 180 (-180 = Norden, -90 = Osten, 0 = Süden, 90 = Westen, 180 = Norden)",
    "ru": "-180… 180 (-180 = север, -90 = восток, 0 = юг, 90 = запад, 180 = север)",
    "pt": "-180… 180 (-180 = norte, -90 = leste, 0 = sul, 90 = oeste, 180 = norte)",
    "nl": "-180… 180 (-180 = noord, -90 = oost, 0 = zuid, 90 = west, 180 = noord)",
    "fr": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ouest, 180 = nord)",
    "it": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ovest, 180 = nord)",
    "es": "-180… 180 (-180 = norte, -90 = este, 0 = sur, 90 = oeste, 180 = norte)",
    "pl": "-180… 180 (-180 = północ, -90 = wschód, 0 = południe, 90 = zachód, 180 = północ)"
  },
  "modules power": {
    "en": "modules power",
    "de": "Leistung Module",
    "ru": "модули питания",
    "pt": "módulos de potência",
    "nl": "modules vermogen",
    "fr": "modules puissance",
    "it": "alimentazione dei moduli",
    "es": "módulos de potencia",
    "pl": "moc modułów"
  },
  "installed power:": {
    "en": "installed power:",
    "de": "Installierte Leistung:",
    "ru": "Установленная мощность:",
    "pt": "poder instalado:",
    "nl": "geïnstalleerd vermogen:",
    "fr": "alimentation branchée:",
    "it": "potenza installata:",
    "es": "potencia instalada:",
    "pl": "zainstalowana moc:"
  },
  "in kWp, deciamal separaion: point": {
    "en": "in kWp, deciamal separaion: point",
    "de": "in kWp, Deziamentrennung: Punkt",
    "ru": "в кВт, десятичное разделение: точка",
    "pt": "em kWp, separação deciamal: point",
    "nl": "in kWp, deciamale scheiding: punt",
    "fr": "en kWc, séparation déciamale: point",
    "it": "in kWp, separazione decimale: punto",
    "es": "en kWp, separación deciamal: punto",
    "pl": "w kWp, separacja deciamalna: punkt"
  }
}
