// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern wird der Adapter sofort mit der neuen Konfiguration neu gestartet",
    "ru": "при сохранении адаптер перезапускается с новым конфигом немедленно",
    "pt": "ao salvar o adaptador reinicia imediatamente com a nova configuração",
    "nl": "on save adapter wordt onmiddellijk opnieuw gestart met de nieuwe configuratie",
    "fr": "lors de l'enregistrement, l'adaptateur redémarre avec la nouvelle configuration immédiatement",
    "it": "on save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "al guardar el adaptador se reinicia con la nueva configuración inmediatamente",
    "pl": "po zapisaniu adapter natychmiast uruchamia się ponownie z nową konfiguracją"
  },
  "host": {
    "en": "Host",
    "de": "Host",
    "ru": "хозяин",
    "pt": "Host",
    "nl": "Host",
    "fr": "Host",
    "it": "Host",
    "es": "Host",
    "pl": "Host"
  },
  "port": {
    "en": "port",
    "de": "Port",
    "ru": "порт",
    "pt": "porta",
    "nl": "port",
    "fr": "Port",
    "it": "porta",
    "es": "Puerto",
    "pl": "Port"
  },
  "pollIntervalcurrent": {
    "en": "polling interval production/consumption (s)",
    "de": "Abfrageintervall Produktion / Verbrauch (e)",
    "ru": "Интервал опроса производство / потребление (а)",
    "pt": "produção / consumo (s) do intervalo de sondagem",
    "nl": "polling interval productie / consumptie (s)",
    "fr": "production / consommation (s) d'intervalle d'interrogation",
    "it": "produzione / consumo (i) dell'intervallo di polling",
    "es": "producción / consumo (s) del intervalo de sondeo",
    "pl": "produkcja / zużycie w interwale sondowania"
  },
  "pollIntervalperiodic": {
    "en": "polling interval average-/sumup values & other (min)",
    "de": "Abfrageintervall Durchschnitts- / Summenwerte & andere (min)",
    "ru": "интервал опроса средние / суммарные значения и другое (мин.)",
    "pt": "média do intervalo de sondagem- / valores de soma e outros (min)",
    "nl": "polling interval gemiddelde- / somwaarden & andere (min)",
    "fr": "Intervalle d'interrogation valeurs moyennes / sommaires et autres (min)",
    "it": "Intervallo di polling valori medi / di riepilogo e altro (min)",
    "es": "Intervalo de sondeo valores promedio / sumatorio y otros (min)",
    "pl": "wartości średnie / sumaryczne interwału odpytywania i inne (min)"
  },
  "invimp": {
    "en": "Import of inverter and other devices data",
    "de": "Importieren von Wechselrichter- und anderen Gerätedaten",
    "ru": "Импорт данных инвертора и других устройств",
    "pt": "Inversor de importação e outros dados de dispositivos",
    "nl": "Importeer gegevens van omvormers en andere apparaten",
    "fr": "Importer les données de l'onduleur et d'autres appareils",
    "it": "Importa i dati dell'inverter e di altri dispositivi",
    "es": "Importar datos del inversor y otros dispositivos",
    "pl": "Importuj dane falownika i innych urządzeń"
  },
  "Basic Settings": {
    "en": "Basic sessting:",
    "de": "Grundeinstellungen",
    "ru": "основные настройки",
    "pt": "configurações básicas",
    "nl": "basis instellingen",
    "fr": "Paramètres de base",
    "it": "impostazioni di base",
    "es": "ajustes básicos",
    "pl": "podstawowe ustawienia"
  },
  "Advanced Settings": {
    "en": "Advanced Settings",
    "de": "Erweiterte Einstellungen",
    "ru": "Расширенные настройки",
    "pt": "Configurações avançadas",
    "nl": "Geavanceerde instellingen",
    "fr": "Réglages avancés",
    "it": "Impostazioni avanzate",
    "es": "Ajustes avanzados",
    "pl": "Zaawansowane ustawienia"
  },
  "Connection settings": {
    "en": "connection settings",
    "de": "Verbindungseinstellungen",
    "ru": "Настройки соединения",
    "pt": "configurações de conexão",
    "nl": "verbindingsinstellingen",
    "fr": "paramètres de connexion",
    "it": "impostazioni di connessione",
    "es": "ajustes de conexión",
    "pl": "ustawienia połączenia"
  },
  "invimp settings": {
    "en": "inverter/submeter settings",
    "de": "Wechselrichter- / Unterzählereinstellungen",
    "ru": "настройки инвертора / пониженной частоты",
    "pt": "configurações do inversor / sub-contador",
    "nl": "omvormer / onderbouw instellingen",
    "fr": "paramètres onduleur / sous comptoir",
    "it": "impostazioni inverter / sottopiano",
    "es": "ajustes del inversor / debajo del mostrador",
    "pl": "ustawienia falownika / podblatowego"
  },
  "get forecast:": {
    "en": "get forecast:",
    "de": "Prognose erhalten:",
    "ru": "получить прогноз:",
    "pt": "obter previsão:",
    "nl": "voorspelling krijgen:",
    "fr": "obtenir des prévisions:",
    "it": "ottenere previsioni:",
    "es": "obtener pronóstico:",
    "pl": "uzyskaj prognozę:"
  },
  "-90 (south) … 90 (north), decimal separation: point": {
    "en": "-90 (south) … 90 (north), decimal separaion: point",
    "de": "-90 (Süden)… 90 (Norden), Dezimaltrennung: Punkt",
    "ru": "-90 (юг)… 90 (север), десятичное разделение: точка",
    "pt": "-90 (sul)… 90 (norte), separação decimal: ponto",
    "nl": "-90 (zuiden) ... 90 (noorden), decimale scheiding: punt",
    "fr": "-90 (sud)… 90 (nord), séparation décimale: point",
    "it": "-90 (sud)… 90 (nord), separaion decimale: punto",
    "es": "-90 (sur) ... 90 (norte), separación decimal: punto",
    "pl": "-90 (południe)… 90 (północ), separacja decimalna: punkt"
  },
  " -180 (west) … 180 (east), decimal separation: point": {
    "en": " -180 (west) … 180 (east), decimal separaion: point",
    "de": " -180 (Westen)… 180 (Osten), Dezimaltrennung: Punkt",
    "ru": " -180 (запад)… 180 (восток), десятичное разделение: точка",
    "pt": " -180 (oeste)… 180 (leste), separação decimal: ponto",
    "nl": " -180 (west) ... 180 (oost), decimale scheiding: punt",
    "fr": " -180 (ouest)… 180 (est), séparation décimale: point",
    "it": " -180 (ovest)… 180 (est), separazione decimale: punto",
    "es": " -180 (oeste) ... 180 (este), separación decimal: punto",
    "pl": " -180 (zachód)… 180 (wschód), separacja decimalna: punkt"
  },
  "latitude:": {
    "en": "latitude:",
    "de": "Breitengrad:",
    "ru": "широта:",
    "pt": "latitude:",
    "nl": "breedtegraad:",
    "fr": "latitude:",
    "it": "latitudine:",
    "es": "latitud:",
    "pl": "szerokość:"
  },
  "longitude:": {
    "en": "longitude:",
    "de": "Längengrad:",
    "ru": "долгота:",
    "pt": "longitude:",
    "nl": "Lengtegraad:",
    "fr": "longitude:",
    "it": "longitudine:",
    "es": "longitud:",
    "pl": "długość geograficzna:"
  },
  "location": {
    "en": "location",
    "de": "Standort",
    "ru": "место расположения",
    "pt": "localização",
    "nl": "plaats",
    "fr": "emplacement",
    "it": "Posizione",
    "es": "ubicación",
    "pl": "Lokalizacja"
  },
  "declination": {
    "en": "declination",
    "de": "Ausrichtung",
    "ru": "склонение",
    "pt": "declinação",
    "nl": "declinatie",
    "fr": "déclinaison",
    "it": "declinazione",
    "es": "declinación",
    "pl": "deklinacja"
  },
  "inclination:": {
    "en": "inclination:",
    "de": "Neigung:",
    "ru": "наклонение:",
    "pt": "inclinação:",
    "nl": "helling:",
    "fr": "inclination:",
    "it": "inclinazione:",
    "es": "inclinación:",
    "pl": "nachylenie:"
  },
  "azimuth:": {
    "en": "azimuth:",
    "de": "Azimut:",
    "ru": "азимут:",
    "pt": "azimute:",
    "nl": "azimuth:",
    "fr": "azimut:",
    "it": "azimut:",
    "es": "azimut:",
    "pl": "azymut:"
  },
  "0 (horizontal) … 90 (vertical)": {
    "en": "0 (horizontal) … 90 (vertical)",
    "de": "0 (horizontal)… 90 (vertikal)",
    "ru": "0 (по горизонтали)… 90 (по вертикали)",
    "pt": "0 (horizontal)… 90 (vertical)",
    "nl": "0 (horizontaal)… 90 (verticaal)",
    "fr": "0 (horizontal)… 90 (vertical)",
    "it": "0 (orizzontale)… 90 (verticale)",
    "es": "0 (horizontal) ... 90 (vertical)",
    "pl": "0 (poziomo)… 90 (pionowo)"
  },
  "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)": {
    "en": "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)",
    "de": "-180… 180 (-180 = Norden, -90 = Osten, 0 = Süden, 90 = Westen, 180 = Norden)",
    "ru": "-180… 180 (-180 = север, -90 = восток, 0 = юг, 90 = запад, 180 = север)",
    "pt": "-180… 180 (-180 = norte, -90 = leste, 0 = sul, 90 = oeste, 180 = norte)",
    "nl": "-180… 180 (-180 = noord, -90 = oost, 0 = zuid, 90 = west, 180 = noord)",
    "fr": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ouest, 180 = nord)",
    "it": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ovest, 180 = nord)",
    "es": "-180… 180 (-180 = norte, -90 = este, 0 = sur, 90 = oeste, 180 = norte)",
    "pl": "-180… 180 (-180 = północ, -90 = wschód, 0 = południe, 90 = zachód, 180 = północ)"
  },
  "modules power": {
    "en": "modules power",
    "de": "Leistung Module",
    "ru": "модули питания",
    "pt": "módulos de potência",
    "nl": "modules vermogen",
    "fr": "modules puissance",
    "it": "alimentazione dei moduli",
    "es": "módulos de potencia",
    "pl": "moc modułów"
  },
  "installed power:": {
    "en": "installed power:",
    "de": "Installierte Leistung:",
    "ru": "Установленная мощность:",
    "pt": "poder instalado:",
    "nl": "geïnstalleerd vermogen:",
    "fr": "alimentation branchée:",
    "it": "potenza installata:",
    "es": "potencia instalada:",
    "pl": "zainstalowana moc:"
  },
  "in kWp, deciamal separaion: point": {
    "en": "in kWp, deciamal separaion: point",
    "de": "in kWp, Deziamentrennung: Punkt",
    "ru": "в кВт, десятичное разделение: точка",
    "pt": "em kWp, separação deciamal: point",
    "nl": "in kWp, deciamale scheiding: punt",
    "fr": "en kWc, séparation déciamale: point",
    "it": "in kWp, separazione decimale: punto",
    "es": "en kWp, separación deciamal: punto",
    "pl": "w kWp, separacja deciamalna: punkt"
  },
  "user": {
    "en": "user",
    "de": "Benutzer",
    "ru": "пользователь",
    "pt": "do utilizador",
    "nl": "gebruiker",
    "fr": "utilisateur",
    "it": "utente",
    "es": "usuario",
    "pl": "użytkownik"
  },
  "password": {
    "en": "password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "senha",
    "nl": "wachtwoord",
    "fr": "mot de passe",
    "it": "parola d'ordine",
    "es": "contraseña",
    "pl": "hasło"
  },
  "historic": {
    "en": "retrieve historic values.   time:",
    "de": "Historische Werte abrufen.    Zeit:",
    "ru": "восстановить исторические ценности.   время:",
    "pt": "recuperar valores históricos.   Tempo:",
    "nl": "historische waarden ophalen.   tijd:",
    "fr": "récupérer des valeurs historiques.   temps:",
    "it": "recuperare valori storici.   tempo:",
    "es": "recuperar valores históricos   hora:",
    "pl": "odzyskać historyczne wartości.   czas:"
  },
  "histhour": {
    "en": "hour",
    "de": "Stunde",
    "ru": "час",
    "pt": "hora",
    "nl": "uur",
    "fr": "heure",
    "it": "ora",
    "es": "hora",
    "pl": "godzina"
  },
  "histmin": {
    "en": "minute",
    "de": "Minute",
    "ru": "минут",
    "pt": "minuto",
    "nl": "minuut",
    "fr": "minute",
    "it": "minuto",
    "es": "minuto",
    "pl": "minuta"
  },
  "userpass": {
    "en": "user password activated",
    "de": "Benutzerpasswort aktiviert",
    "ru": "пароль пользователя активирован",
    "pt": "senha de usuário ativada",
    "nl": "gebruikerswachtwoord geactiveerd",
    "fr": "mot de passe utilisateur activé",
    "it": "password utente attivata",
    "es": "contraseña de usuario activada",
    "pl": "hasło użytkownika zostało aktywowane"
  },
  "userpw": {
    "en": "user password",
    "de": "Benutzer-Passwort",
    "ru": "пользовательский пароль",
    "pt": "senha do usuário",
    "nl": "gebruikerswachtwoord",
    "fr": "mot de passe de l'utilisateur",
    "it": "password utente",
    "es": "contraseña de usuario",
    "pl": "hasło użytkownika"
  }
}
