// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "ÐÐ²Ñ‚Ð¾Ð¼Ð°Ñ‚Ð¸Ñ‡ÐµÑÐºÐ¸",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Ð’Ñ€ÑƒÑ‡Ð½ÑƒÑŽ",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual"
  },
  "My select": {
    "en": "My select",
    "de": "Mein Auswahl",
    "ru": "Ð’Ñ‹Ð±Ð¾Ñ€",
    "pt": "Meu selecionado",
    "nl": "Mijn select",
    "fr": "Mon choix",
    "it": "La mia selezione",
    "es": "Mi seleccion"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "ÐŸÑ€Ð¸ ÑÐ¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ð¸ Ð½Ð°ÑÑ‚Ñ€Ð¾ÐµÐº Ð°Ð´Ð°Ð¿Ñ‚ÐµÑ€Ð° Ð¾Ð½ ÑÑ€Ð°Ð·Ñƒ Ð¶Ðµ Ð¿ÐµÑ€ÐµÐ·Ð°Ð¿ÑƒÑÐºÐ°ÐµÑ‚ÑÑ",
    "pt": "no adaptador de salvar reinicia com nova configuraÃ§Ã£o imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redÃ©marre avec la nouvelle config immÃ©diatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuraciÃ³n de inmediato"
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel",
    "ru": "ÐŸÑ€Ð¸Ð¼ÐµÑ€",
    "pt": "configuraÃ§Ãµes do adaptador de modelo",
    "nl": "sjabloon-adapterinstellingen",
    "fr": "paramÃ¨tres de l'adaptateur de modÃ¨le",
    "it": "impostazioni dell'adattatore del modello",
    "es": "configuraciÃ³n del adaptador de plantilla"
  },
  "host": {
    "en": "Solarlog IP:",
    "de": "Solarlog IP:",
    "ru": "Solarlog IP:",
    "pt": "Solarlog IP:",
    "nl": "Solarlog IP:",
    "fr": "Solarlog IP:",
    "it": "Solarlog IP:",
    "es": "Solarlog IP:"
  },
  "port": {
    "en": "Port (optional):",
    "de": "Port (optional):",
    "ru": "Port (optional):",
    "pt": "Port (optional):",
    "nl": "Port (optional):",
    "fr": "Port (optional):",
    "it": "Port (optional):",
    "es": "Port (optional):"
  },
  "pollInterval": {
    "en": "Polling - Intervall (ms):",
    "de": "Abfrage - Intervall (ms):",
    "ru": "Abfrage - Intervall (ms):",
    "pt": "Polling - Intervall (ms):",
    "nl": "Polling - Intervall (ms):",
    "fr": "Polling - Intervall (ms):",
    "it": "Polling - Intervall (ms):",
    "es": "Polling - Intervall (ms):"
  },
  "invimp": {
    "en": "inverter/undercounter request. Caution! User-password of Solarlog has to be deactivated",
    "de": "Wechselrichter- / Unterzähleranforderung. Vorsicht! Das Benutzerpasswort von Solarlog muss deaktiviert sein",
    "ru": "запрос инвертора / пониженной нагрузки. Внимание! Пароль пользователя Solarlog должен быть деактивирован",
    "pt": "solicitação do inversor / sub-contador. Cuidado! A senha do usuário do Solarlog deve ser desativada",
    "nl": "verzoek omvormer / onderbouw. Voorzichtigheid! Het gebruikerswachtwoord van Solarlog moet worden gedeactiveerd",
    "fr": "onduleur / demande sous comptoir. Mise en garde! Le mot de passe utilisateur de Solarlog doit être désactivé",
    "it": "richiesta inverter / sottopiano. Attenzione! La password utente di Solarlog deve essere disattivata",
    "es": "solicitud de inversor / bajo mostrador. ¡Precaución! La contraseña de usuario de Solarlog debe estar desactivada",
    "pl": "zapytanie o falownik / podblat. Uwaga! Hasło użytkownika Solarlog musi zostać dezaktywowane",
    "zh-cn": "逆变器/台下设备请求。警告！必须禁用Solarlog的用户密码"
  },
  "Basic Settings": {
    "en": "Basic sessting:",
    "de": "Grundeinstellungen",
    "ru": "основные настройки",
    "pt": "configurações básicas",
    "nl": "basis instellingen",
    "fr": "Paramètres de base",
    "it": "impostazioni di base",
    "es": "ajustes básicos",
    "pl": "podstawowe ustawienia",
    "zh-cn": "基本设置"
  },
  "Plant Settings": {
    "en": "plant settings",
    "de": "Anlageneinstellungen",
    "ru": "заводские настройки",
    "pt": "configurações da planta",
    "nl": "plant instellingen",
    "fr": "paramètres de l'usine",
    "it": "impostazioni dell'impianto",
    "es": "ajustes de la planta",
    "pl": "ustawienia roślin",
    "zh-cn": "工厂设置"
  },
  "Connection settings": {
    "en": "connection settings",
    "de": "Verbindungseinstellungen",
    "ru": "Настройки соединения",
    "pt": "configurações de conexão",
    "nl": "verbindingsinstellingen",
    "fr": "paramètres de connexion",
    "it": "impostazioni di connessione",
    "es": "ajustes de conexión",
    "pl": "ustawienia połączenia",
    "zh-cn": "连接设置"
  },
  "invimp settings": {
    "en": "inverter/submeter settings",
    "de": "Wechselrichter- / Unterzählereinstellungen",
    "ru": "настройки инвертора / пониженной частоты",
    "pt": "configurações do inversor / sub-contador",
    "nl": "omvormer / onderbouw instellingen",
    "fr": "paramètres onduleur / sous comptoir",
    "it": "impostazioni inverter / sottopiano",
    "es": "ajustes del inversor / debajo del mostrador",
    "pl": "ustawienia falownika / podblatowego",
    "zh-cn": "逆变器/台下设置"
  },
  "get forecast:": {
    "en": "get forecast:",
    "de": "Prognose erhalten:",
    "ru": "получить прогноз:",
    "pt": "obter previsão:",
    "nl": "voorspelling krijgen:",
    "fr": "obtenir des prévisions:",
    "it": "ottenere previsioni:",
    "es": "obtener pronóstico:",
    "pl": "uzyskaj prognozę:",
    "zh-cn": "得到预测："
  }
  "-90 (south) … 90 (north), deciamal separaion: point": {
    "en": "-90 (south) … 90 (north), deciamal separaion: point",
    "de": "-90 (Süden)… 90 (Norden), Deziamentrennung: Punkt",
    "ru": "-90 (юг)… 90 (север), десятичное разделение: точка",
    "pt": "-90 (sul)… 90 (norte), separação deciamal: ponto",
    "nl": "-90 (zuiden) ... 90 (noorden), deciamale scheiding: punt",
    "fr": "-90 (sud)… 90 (nord), séparation déciamale: point",
    "it": "-90 (sud)… 90 (nord), separaion deciamale: punto",
    "es": "-90 (sur) ... 90 (norte), separación deciamal: punto",
    "pl": "-90 (południe)… 90 (północ), separacja deciamalna: punkt",
    "zh-cn": "-90（向南）…90（向北），蜕膜分离：点"
  },
  " -180 (west) … 180 (east), deciamal separaion: point": {
    "en": " -180 (west) … 180 (east), deciamal separaion: point",
    "de": " -180 (Westen)… 180 (Osten), Deziamaltrennung: Punkt",
    "ru": " -180 (запад)… 180 (восток), десятичное разделение: точка",
    "pt": " -180 (oeste)… 180 (leste), separação deciamal: ponto",
    "nl": " -180 (west) ... 180 (oost), deciamale scheiding: punt",
    "fr": " -180 (ouest)… 180 (est), séparation déciamale: point",
    "it": " -180 (ovest)… 180 (est), separazione deciamale: punto",
    "es": " -180 (oeste) ... 180 (este), separación deciamal: punto",
    "pl": " -180 (zachód)… 180 (wschód), separacja deciamalna: punkt",
    "zh-cn": " -180（西）…180（东），分离性分裂：点"
  },
  "latitude:": {
    "en": "latitude:",
    "de": "Breitengrad:",
    "ru": "широта:",
    "pt": "latitude:",
    "nl": "breedtegraad:",
    "fr": "latitude:",
    "it": "latitudine:",
    "es": "latitud:",
    "pl": "szerokość:",
    "zh-cn": "纬度："
  },
  "longitude:": {
    "en": "longitude:",
    "de": "Längengrad:",
    "ru": "долгота:",
    "pt": "longitude:",
    "nl": "Lengtegraad:",
    "fr": "longitude:",
    "it": "longitudine:",
    "es": "longitud:",
    "pl": "długość geograficzna:",
    "zh-cn": "经度："
  },
  "location": {
    "en": "location",
    "de": "Standort",
    "ru": "место расположения",
    "pt": "localização",
    "nl": "plaats",
    "fr": "emplacement",
    "it": "Posizione",
    "es": "ubicación",
    "pl": "Lokalizacja",
    "zh-cn": "地点"
  },
  "declination": {
    "en": "declination",
    "de": "Ausrichtung",
    "ru": "склонение",
    "pt": "declinação",
    "nl": "declinatie",
    "fr": "déclinaison",
    "it": "declinazione",
    "es": "declinación",
    "pl": "deklinacja",
    "zh-cn": "磁偏角"
  },
  "inclination:": {
    "en": "inclination:",
    "de": "Neigung:",
    "ru": "наклонение:",
    "pt": "inclinação:",
    "nl": "helling:",
    "fr": "inclination:",
    "it": "inclinazione:",
    "es": "inclinación:",
    "pl": "nachylenie:",
    "zh-cn": "倾角"
  },
  "azimuth:": {
    "en": "azimuth:",
    "de": "Azimut:",
    "ru": "азимут:",
    "pt": "azimute:",
    "nl": "azimuth:",
    "fr": "azimut:",
    "it": "azimut:",
    "es": "azimut:",
    "pl": "azymut:",
    "zh-cn": "方位角"
  },
  "0 (horizontal) … 90 (vertical)": {
    "en": "0 (horizontal) … 90 (vertical)",
    "de": "0 (horizontal)… 90 (vertikal)",
    "ru": "0 (по горизонтали)… 90 (по вертикали)",
    "pt": "0 (horizontal)… 90 (vertical)",
    "nl": "0 (horizontaal)… 90 (verticaal)",
    "fr": "0 (horizontal)… 90 (vertical)",
    "it": "0 (orizzontale)… 90 (verticale)",
    "es": "0 (horizontal) ... 90 (vertical)",
    "pl": "0 (poziomo)… 90 (pionowo)",
    "zh-cn": "0（水平）…90（垂直）"
  },
  "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)": {
    "en": "-180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)",
    "de": "-180… 180 (-180 = Norden, -90 = Osten, 0 = Süden, 90 = Westen, 180 = Norden)",
    "ru": "-180… 180 (-180 = север, -90 = восток, 0 = юг, 90 = запад, 180 = север)",
    "pt": "-180… 180 (-180 = norte, -90 = leste, 0 = sul, 90 = oeste, 180 = norte)",
    "nl": "-180… 180 (-180 = noord, -90 = oost, 0 = zuid, 90 = west, 180 = noord)",
    "fr": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ouest, 180 = nord)",
    "it": "-180… 180 (-180 = nord, -90 = est, 0 = sud, 90 = ovest, 180 = nord)",
    "es": "-180… 180 (-180 = norte, -90 = este, 0 = sur, 90 = oeste, 180 = norte)",
    "pl": "-180… 180 (-180 = północ, -90 = wschód, 0 = południe, 90 = zachód, 180 = północ)",
    "zh-cn": "-180…180（-180 =北方，-90 =东方，0 =南方，90 =西方，180 =北方）"
  },
  "modules power": {
    "en": "modules power",
    "de": "Leistung Module",
    "ru": "модули питания",
    "pt": "módulos de potência",
    "nl": "modules vermogen",
    "fr": "modules puissance",
    "it": "alimentazione dei moduli",
    "es": "módulos de potencia",
    "pl": "moc modułów",
    "zh-cn": "模块电源"
  },
  "installed power:": {
    "en": "installed power:",
    "de": "Installierte Leistung:",
    "ru": "Установленная мощность:",
    "pt": "poder instalado:",
    "nl": "geïnstalleerd vermogen:",
    "fr": "alimentation branchée:",
    "it": "potenza installata:",
    "es": "potencia instalada:",
    "pl": "zainstalowana moc:",
    "zh-cn": "装机功率"
  },
  "in kWp, deciamal separaion: point": {
    "en": "in kWp, deciamal separaion: point",
    "de": "in kWp, Deziamentrennung: Punkt",
    "ru": "в кВт, десятичное разделение: точка",
    "pt": "em kWp, separação deciamal: point",
    "nl": "in kWp, deciamale scheiding: punt",
    "fr": "en kWc, séparation déciamale: point",
    "it": "in kWp, separazione decimale: punto",
    "es": "en kWp, separación deciamal: punto",
    "pl": "w kWp, separacja deciamalna: punkt",
    "zh-cn": "以kWp为单位，蜕膜分离：点"
  }
}
